#Minecraft server properties
#Mon May 11 10:34:13 MSK 2026
level-name=world
view-distance=10
white-list=false
server-ip=
pvp=true
level-seed=
spawn-animals=true
server-port=25565
allow-nether=true
spawn-monsters=true
max-players=20
online-mode=true
allow-flight=false
